name: Run ESLint and Prettier

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run ESLint and Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.15.0
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn@1.22.19

      - name: Install dependencies
        run: yarn install --frozen-lockfile --silent --ignore-optional

      - name: Run ESLint
        run: yarn office-addin-lint check --files src/**/*.{ts,tsx}

      - name: Run Prettier
        run: yarn office-addin-lint prettier --files src/**/*.{ts,tsx}